/** Hebrew UI strings */
export default {
  appTitle: 'מערכת בקרת מעבדה',
  allProjects: 'כל הפרויקטים',
  projects: 'פרויקטים',
  newProject: 'פרויקט חדש',
  cancel: 'ביטול',
  create: 'צור',
  name: 'שם',
  description: 'תיאור',
  optional: 'אופציונלי',
  noDescription: 'אין תיאור',
  loading: 'טוען...',
  noProjectsYet: 'עדיין אין פרויקטים. צור אחד למעלה.',
  back: 'חזרה',

  overview: 'סקירה',
  overviewAnalytics: 'אנליטיקה',
  taskStatusBreakdown: 'התפלגות משימות',
  overdueTasks: 'משימות באיחור',
  milestonesProgress: 'התקדמות אבני דרך',
  byPriority: 'לפי עדיפות',
  noOverdue: 'אין משימות באיחור',
  completedMilestones: 'אבני דרך שהושלמו',
  tasks: 'משימות',
  milestones: 'אבני דרך',
  documents: 'מסמכים',
  notes: 'הערות',
  files: 'קבצים',
  rag: 'שאלות ותשובות',
  reports: 'דוחות',
  activity: 'פעילות',

  tasksCount: 'משימות',
  milestonesCount: 'אבני דרך',
  documentsCount: 'מסמכים',
  notesCount: 'הערות',
  filesCount: 'קבצים',

  addTask: 'הוסף משימה',
  taskTitle: 'כותרת משימה',
  todo: 'לביצוע',
  inProgress: 'בביצוע',
  inReview: 'בבדיקה',
  done: 'הושלם',
  cancelled: 'בוטל',
  low: 'נמוך',
  medium: 'בינוני',
  high: 'גבוה',
  add: 'הוסף',
  delete: 'מחיקה',
  deleteTaskConfirm: 'למחוק את המשימה?',
  noTasksYet: 'עדיין אין משימות',
  overdue: 'באיחור',
  markSelectedDone: 'סמן נבחרים כהושלמו',
  selectAll: 'בחר הכל',

  addMilestone: 'הוסף אבן דרך',
  sortByTitle: 'לפי כותרת',

  exportSummary: 'ייצא סיכום פרויקט',
  copyAnswer: 'העתק תשובה',
  copySuccess: 'הועתק ללוח',
  saveAnswerAsNote: 'שמור כהערה',
  saveAsNoteSuccess: 'נשמר כהערה בפרויקט',

  milestoneTitle: 'כותרת אבן דרך',
  deleteMilestoneConfirm: 'למחוק את אבן הדרך?',
  noMilestonesYet: 'עדיין אין אבני דרך',
  markAsCompleted: 'סמן כמושלמה',
  unmarkCompleted: 'בטל סימון',

  addDocument: 'הוסף מסמך',
  documentTitle: 'כותרת מסמך',
  content: 'תוכן',
  optionalContent: 'תוכן אופציונלי',
  save: 'שמירה',
  edit: 'עריכה',
  deleteDocumentConfirm: 'למחוק את המסמך?',
  noDocumentsYet: 'עדיין אין מסמכים',

  addNote: 'הוסף הערה',
  noteTitle: 'כותרת הערה',
  noteContent: 'תוכן ההערה',
  body: 'גוף',
  untitled: 'ללא כותרת',
  deleteNoteConfirm: 'למחוק את ההערה?',
  noNotesYet: 'עדיין אין הערות',

  uploadedFiles: 'קבצים שהועלו',
  uploadedFilesDesc: 'העלה PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה ואפשר לשאול עליהם בלשונית שאלות.',
  chooseFile: 'בחר קובץ להעלאה',
  chooseFileMultiple: 'העלה קבצים מהמחשב שלך',
  uploadFromComputer: 'העלה מהמחשב',
  uploadChoiceTitle: 'מה להעלות?',
  uploadFilesOption: 'קבצים',
  uploadFolderOption: 'תיקייה',
  chooseFromSharepoint: 'ייבוא קבצים מ-SharePoint',
  uploadToSharepoint: 'העלה קבצים/תיקיות ל-SharePoint',
  uploadToSharepointManual: 'העלה קובץ או תיקייה ידנית',
  sharepointFolderPath: 'נתיב תיקייה (אופציונלי)',
  sharepointFolderName: 'שם תיקייה (לכמה קבצים)',
  sharepointUploadSuccess: 'הקבצים הועלו ל-SharePoint.',
  sharepointUploadSomeFailed: 'חלק מהקבצים לא הועלו.',
  sharepointBucketList: 'קבצים מ-SharePoint',
  addToProject: 'הוסף לפרויקט',
  addFolderToProject: 'הוסף תיקייה לפרויקט',
  loadingSharepointFiles: 'טוען רשימה...',
  noSharepointFiles: 'אין קבצים בדלי.',
  searchSharepointFiles: 'חיפוש קבצים...',
  folder: 'תיקייה',
  uploading: 'מעלה...',
  uploadingProgress: (current, total) => `מעלה ${current} / ${total}`,
  uploadSomeFailed: 'חלק מההעלאות נכשלו:',
  remove: 'הסר',
  removeFileConfirm: 'להסיר את הקובץ מהפרויקט? (הוא יישאר במטריה עד להסרה משם.)',
  noFilesYet: 'עדיין לא הועלו קבצים.',
  noFolder: 'ללא תיקייה',
  fileIndexError: 'קובץ זה לא ניתן לסריקה עקב פורמט לא תואם',
  fileCannotBeIndexed: 'לא ניתן לשאול על קובץ זה – פורמט לא נתמך',
  download: 'הורדה',
  downloadNotAvailable: 'הורדת קובץ תעלה בגרסה הבאה.',

  docsManagementTab: 'ניהול מסמכים',
  docsManagementTitle: 'ניהול מסמכים',
  docsManagementIntro: 'העלה קבצים לפרויקט, הורד אותם או שאל שאלות על התוכן שלהם.',
  docsUploadSection: 'העלאת קבצים',
  docsUploadHint: 'PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה לעיבוד וניתן לשאול עליהם שאלות.',
  docsListSection: 'הקבצים בפרויקט',
  docsAskSection: 'שאל שאלה על המסמכים',

  ragGptOpenAiUnavailable: 'OpenAI לא מוגדר בשרת (הגדר OPENAI_API_KEY ב־maneger-back).',
  gptRagRefreshStatus: 'רענון סטטוס',
  ragGptSyncDone: 'סנכרון הושלם.',
  gptRagResyncShort: 'סנכרון מחדש',
  gptRagIndicatorLoading: 'בודק חיבור OpenAI…',
  gptRagIndicatorSyncing: 'מסנכרן....',
  /** OpenAI vector store still indexing — block Q&A until finished */
  gptRagIndicatorIndexing: 'מאנדקס מסמכים ב־OpenAI… (המתן לפני שאלה)',
  gptRagIndicatorPending: 'ממתין לסנכרון…',
  gptRagIndicatorSynced: 'מסונכרן',
  gptRagIndicatorNoFiles: 'אין קבצים בפרויקט.',
  gptRagIndicatorNoStoragePath:
    'חלק מהמסמכים נרשמו בלי קובץ ב־Storage (אין נתיב אחסון) — סנכרון OpenAI לא יעבוד עליהם. אפשר ללחוץ «שחזור מהאינדוקס» אם המסמכים כבר אונדקסו ב־RAG, או להעלות/למשוך שוב מהמקור.',
  gptRagRepairStorageFromRag: 'שחזור נתיב אחסון מהאינדוקס',
  gptRagRepairStorageRunning: 'משחזר…',
  gptRagIndicatorNoSupportedFiles:
    'אין כרגע מסמכים בפורמט שניתן לחפש ב־OpenAI (למשל PDF, DOCX, TXT, XLSX, PPTX). קבצים אחרים בפרויקט לא נסרקים לשאלות — הוסף מסמך מהסוגים האלה.',
  gptRagIndicatorSyncFailed: 'הסנכרון ל־OpenAI נכשל. בדוק את ההודעה למעלה או נסה שוב.',
  gptRagRetrySync: 'נסה שוב',
  /** Tooltip on disabled «הרץ» when OpenAI selected but no vector store */
  ragGptNoVectorTitle: 'ממתין לסנכרון או אין מסמכים בפורמט נתמך ל־OpenAI',
  /** Tooltip on disabled «הרץ» while document sync is in progress */
  ragGptRunWhileSyncingTitle: 'לא ניתן להריץ בזמן סנכרון המסמכים (מסנכרן…)',
  ragGptAskBlockedUploadTitle: 'לא ניתן לשאול בזמן העלאה או הוספת קבצים — המתן לסיום ולסנכרון.',
  gptRagIndicatorUploadBusy: 'מעלה או מוסיף קבצים… (המתן לפני שאלה)',
  /** Document Q&A: retrieved excerpts shown under the answer */
  ragAnswerSourcesTitle: 'מקורות מהמסמכים (ציטוטים)',
  ragAnswerSourcesHint: 'קטעים שחיפוש המסמכים החזיר לפני ניסוח התשובה — לשקיפות וביקורת.',

  ragTitle: 'שאלות (מטריה)',
  matriyaConnected: 'חיבור למטריה פעיל',
  matriyaNotSet: 'כתובת מטריה לא מוגדרת או לא זמינה (הגדר MATRIYA_BACK_URL ב־.env של maneger-back)',
  ragConnected: 'חיבור ל־RAG פעיל',
  ragNotAvailable: 'חיבור ל־RAG לא פעיל. בדוק ש־POSTGRES_URL ו־OPENAI_API_KEY מוגדרים ב־maneger-back (Vercel).',
  queryOver: 'חיפוש בתוך',
  allFiles: 'כל הקבצים',
  selectFileToAsk: 'בחר קובץ לשאלה',
  askQuestion: 'שאל שאלה',
  questionPlaceholder: 'הזן שאלה...',
  run: 'הרץ',
  running: 'מריץ...',

  title: 'כותרת',
  projectName: 'שם הפרויקט',

  settings: 'הגדרות',
  chat: "צ'אט",
  chatPlaceholder: 'כתוב הודעה...',
  chatSend: 'שלח',
  noChatYet: 'אין הודעות עדיין. תגיד שלום!',
  chatUnreadCount: (n) => n === 1 ? 'הודעה אחת שלא נקראה' : `${n} הודעות שלא נקראו`,
  chatNewMessages: (n) => n === 1 ? 'הודעה חדשה' : `${n} הודעות חדשות`,
  emailsTab: 'מיילים',
  emailTo: 'אל (כתובת)',
  emailSubject: 'נושא',
  emailBody: 'תוכן ההודעה',
  emailSend: 'שלח מייל',
  emailSent: 'המייל נשלח ונשמר בתיבה.',
  emailConfigMissing: 'שליחת מייל לא זמינה – לא הוגדר מפתח Resend בשרת.',
  emailFolderSent: 'נשלחו',
  emailFolderReceived: 'התקבלו',
  emailReceivedSetupHint:
    'אין מיילים נכנסים עדיין. כדי לקבל מיילים לפרויקט: הגדר ב־Resend Inbound Webhook את כתובת ה־API של השרת (כולל מזהה הפרויקט בכתובת היעד), כפי שמופיע ב־.env.example של maneger-back.',
  emailCompose: 'הודעה חדשה',
  emailNoSelection: 'בחר מייל מהרשימה',
  emailEmptyList: 'אין מיילים בתיקייה זו.',
  emailFrom: 'מאת',
  emailToLabel: 'אל',
  emailDate: 'תאריך',
  emailLoadError: 'טעינת מיילים נכשלה',
  emailAttachments: 'קבצים מצורפים',
  emailImportToDocuments: 'ייבא למסמכי הפרויקט',
  emailImportToLab: 'ייבא למעבדה',
  emailImporting: 'מייבא…',
  emailImportDone: 'הקובץ יובא. אפשר לפתוח את לשונית המסמכים או המעבדה.',
  emailImportLabLoading: 'טוען קובץ מהמייל למעבדה…',
  emailImportLabParseError: 'לא הצלחנו לטעון את הקובץ למעבדה. נסה שוב או העלה את הקובץ ידנית.',
  emailNoAttachments: 'אין קבצים מצורפים במייל זה (או המייל נשמר לפני תמיכה במצורפים).',
  emailSentBy: 'נשלח על ידי',
  emailAttachFromProject: 'צרף קבצים ממסמכי הפרויקט',
  emailAttachmentsComposeLabel: 'קבצים מצורפים',
  emailAttachFromProjectBtn: 'בחר מהפרויקט',
  emailAttachFromPcBtn: 'העלה מהמחשב',
  emailAttachModalTitle: 'בחירת קבצים ממסמכי הפרויקט',
  emailAttachModalClose: 'סגור',
  emailAttachTooMany: 'ניתן לצרף לכל היותר 15 קבצים בסך הכל (מהפרויקט ומהמחשב).',
  emailAttachReadError: 'קריאת קובץ מהמחשב נכשלה. נסה קובץ אחר.',
  emailAttachNoFiles: 'אין קבצים ברשימת המסמכים. העלה או סנכרן קבצים בלשונית המסמכים.',
  emailAttachNoAttachableFiles:
    'אין כרגע קבצים שניתן לצרף מהמסמכים. מוצגים כאן רק קבצים שנשמרו באחסון הפרויקט — העלה מחדש או סנכרן מ־SharePoint.',
  emailAttachNoStorageShort: 'לא זמין לצירוף',
  emailAttachNoStorage:
    'קובץ זה לא שמור באחסון הפרויקט (למשל הועלה ישירות ל־RAG בלי נתיב). רק קבצים עם אחסון (SharePoint / מסמכים) ניתנים לצירוף.',
  projectSettings: 'הגדרות פרויקט',
  editProject: 'ערוך פרויקט',
  deleteProject: 'מחיקת הפרויקט',
  deleteProjectConfirm: 'למחוק את הפרויקט וכל התוכן שלו (משימות, אבני דרך, מסמכים, הערות, קבצים)? לא ניתן לשחזר.',
  deleteProjectSuccess: 'הפרויקט נמחק.',
  saveChanges: 'שמור שינויים',

  dueDate: 'תאריך יעד',
  filterStatus: 'סנן לפי סטטוס',
  filterAll: 'הכל',
  sortBy: 'מיין לפי',
  sortByDate: 'תאריך',
  sortByPriority: 'עדיפות',

  milestoneDescription: 'תיאור אבן דרך',
  upcomingMilestones: 'אבני דרך קרובות',
  noUpcomingMilestones: 'אין אבני דרך קרובות.',
  taskProgress: 'התקדמות משימות',
  completed: 'הושלמו',

  searchProjects: 'חיפוש פרויקטים...',
  searchInList: 'חיפוש ברשימה...',
  noResults: 'לא נמצאו תוצאות.',

  notPartOfProject: 'אינך חלק מפרויקט זה.',
  sendRequestToOwner: 'שלח בקשת הצטרפות למנהל הפרויקט',
  requestPending: 'בקשתך ממתינה לאישור.',
  requestSent: 'הבקשה נשלחה.',
  members: 'חברים בפרויקט',
  pendingRequests: 'בקשות ממתינות',
  addMember: 'הוסף משתמש',
  addMemberPlaceholder: 'שם משתמש',
  selectUser: 'בחר משתמש',
  noUsersToAdd: 'אין משתמשים להוספה (כולם כבר בפרויקט, או שמשתמשים טרם התחברו למנהל).',
  approve: 'אשר',
  reject: 'דחה',
  owner: 'מנהל',
  member: 'חבר',
  userNotFound: 'משתמש לא נמצא. עליו להתחבר למנהל פעם אחת.',
  alreadyMember: 'כבר חבר בפרויקט.',
  noPendingRequests: 'אין בקשות ממתינות.',
  projectPermissions: 'הרשאות פרויקט',
  comingSoon: "בקרוב – פיצ'ר זה יופיע בגרסה הבאה.",
  removeFromProject: 'הסר מפרויקט',

  login: 'התחברות',
  signup: 'הרשמה',
  logout: 'יציאה',
  username: 'שם משתמש',
  password: 'סיסמה',
  email: 'דוא"ל',
  fullName: 'שם מלא',
  loginTitle: 'מערכת בקרת מעבדה',
  signupTitle: 'הרשמה – משתמשים כמו במטריה',
  loginButton: 'התחבר',
  signupButton: 'הירשם',
  noAccount: 'אין לך חשבון?',
  haveAccount: 'כבר יש לך חשבון?',
  loginError: 'שם משתמש או סיסמה שגויים.',
  signupError: 'ההרשמה נכשלה.',

  labTab: 'מעבדה',
  materialLibraryTab: 'ספריית חומרים',
  materialLibraryTitle: 'ספריית חומרים',
  materialLibraryIntro: 'מילון חומרים לפי פרויקט, כולל קישור לניסויים בפועל.',
  materialRoleOrFunction: 'תפקיד / פונקציה',
  linkedExperiments: 'ניסויים מקושרים',
  addMaterialToLibrary: 'הוסף חומר לספרייה',
  materialNamePlaceholder: 'שם חומר',
  noMaterialsYet: 'עדיין אין חומרים בספרייה.',
  labExperiments: 'ניסויים',
  labExperimentsList: 'רשימת ניסויים',
  labExperimentsCount: (n) => `${n} ניסויים`,
  labSessionsCount: (n) => `${n} סשני מחקר`,
  labMaterialsCount: (n) => `${n} חומרים בספרייה`,
  labInsights: 'תובנות מהדאטה',
  labInsightsSummary: 'סיכום:',
  labSuccessRate: 'הצלחה',
  labFailures: 'כישלונות',
  labByDomain: 'לפי תחום',
  labByMaterial: 'לפי חומר (בכישלונות)',
  labLoadInsights: 'לחץ רענן לטעינת תובנות.',
  labContradictions: 'זיהוי סתירות',
  labContradictionsFound: (n) => `נמצאו ${n} סתירות (אותה פורמולה, תוצאות שונות).`,
  labNoContradictions: 'לא נמצאו סתירות.',
  labSameFormulaDifferentOutcomes: 'אותה פורמולה – תוצאות שונות:',
  labFailurePatterns: 'דפוסי כישלון',
  labFailureCount: (n) => `${n} ניסויים נכשלו או חלקיים.`,
  labResearchSnapshot: 'ניתוח סנאפשוט מחקר',
  labSnapshotTotal: (n) => `סה"כ ${n} ניסויים בסנאפשוט.`,
  labFormulaValidator: 'אימות פורמולה (בסיסי)',
  labComparisonPercentages: 'השוואה עם אחוזים (A מול B)',
  labComparisonPercentagesHint:
    'טבלה דטרמיניסטית: רכיב, % לכל גרסה, ו־Δ (B−A) במספרים מדויקים. אפשרות א׳: שני ניסויים מהמאגר (אם יש להם percentages). אפשרות ב׳: שתי טבלאות Markdown נפרדות. אפשרות ג׳: טבלה אחת עם שתי עמודות % — הדבק בשדה הראשון בלבד.',
  labComparisonLabelA: 'תווית גרסה A',
  labComparisonLabelB: 'תווית גרסה B',
  labComparisonTextA: 'טקסט / טבלת Markdown — גרסה A (או טבלה עם שתי עמודות %)',
  labComparisonTextB: 'טקסט / טבלת Markdown — גרסה B',
  labComparisonExperimentA: 'ניסוי A (מזהה)',
  labComparisonExperimentB: 'ניסוי B (מזהה)',
  labComparisonRun: 'השוואה',
  labComparisonFromContextA: 'העתק מהקשר למעלה → A',
  labComparisonFromContextB: 'העתק מהקשר למעלה → B',
  labComparisonPickExperiment: '— בחרו ניסוי —',
  labComparisonNeedInput: 'בחרו שני ניסויים, או מלאו טקסט לשני השדות, או טבלה אחת עם שני % בשדה הראשון.',
  ragComparePercentagesLabHint:
    'להשוואת הרכב A מול B עם Δ מדויקים: השתמשו בלשונית מעבדה → «השוואה עם אחוזים». כאן (חיפוש במסמכים) — אם השאלה על השוואה, ענו בטבלת Markdown: רכיב | % A | % B | Δ (B−A) רק מנתונים בציטוטים.',
  labFormulaPlaceholder: 'הדבק פורמולה או הרכב...',
  labFormulaValid: 'הפורמולה תקינה.',
  labFormulaInvalid: 'נמצאו בעיות בפורמולה.',
  labSimilarExperiments: 'ניסויים דומים',
  labRelations: 'קשרים (ניסוי / פורמולה / חומר / תוצאה)',
  labRelationsSummary: (expCount, matCount) => `${expCount} ניסויים, ${matCount} חומרים בספרייה.`,
  labRelationsList: 'קשרים נגזרים מהדאטה:',
  labResearchGuard: 'Research Guard',
  labSuggestionEngine: 'Suggestion Engine',
  labAnalysisType: 'סוג ניתוח',
  labSuggestionEngineHint: 'מנוע ההצעות מנתח ניסויים קיימים ומציע 3–5 ניסויים חדשים. לכל הצעה: פורמולציה, הסבר, Evidence (על בסיס מה ההצעה), ו־Risk בסיסי. הזן או העלה נתוני ניסוי למעלה ולחץ לקבלת הצעות.',
  labGuardPlaceholder: 'הדבק פורמולה לבדיקה (כפילות, אזהרות)...',
  labGuardAllowed: 'מותר להמשיך.',
  labGuardBlocked: 'קיימות אזהרות.',
  labShowingFirst: (n) => `מציג את ${n} הראשונים.`,

  labFormulationIntelligence: 'Formulation Intelligence',
  labFormulationIntelligenceHint: 'בדיקה לפני ניסוי: מאזן מסה, טווחים, התאמה לניסויים שנכשלו.',
  labFormulationPlaceholder: 'פורמולה או JSON: { "formula": "...", "domain": "...", "materials": [], "percentages": {} }',
  labSaveAsExperiment: 'שמירה כניסוי במעבדה',
  labSaveAsExperimentHint:
    'נשמר ב־lab_experiments (תוצאות ריקות, סטטוס partial) וב־experiment_materials לפי חומרים ואחוזים. דורש טבלת experiment_materials ב-Supabase (ראה maneger-back/sql/create_experiment_materials.sql).',
  labSaveExperimentIdOptional: 'מזהה ניסוי (אופציונלי)',
  labFormulationSaveNeedInput: 'הזן פורמולה או JSON עם פורמולה/חומרים לפני השמירה.',
  labSaveAsExperimentSuccess: (id) => `נשמר. experiment_id: ${id}`,
  labSaveAsExperimentMaterialsCount: (n) => (n > 0 ? `נשמרו ${n} רשומות ב־experiment_materials.` : ''),
  labStatus: 'סטטוס',
  labSimilarExperimentsTitle: 'ניסויים דומים',
  labSimilarExperimentsHint: 'הזן מזהה ניסוי (experiment_id או id) כדי למצוא ניסויים דומים לפי חומרים ופרופורציות.',
  labExperimentIdPlaceholder: 'experiment_id או UUID',
  labSimilarTo: (id) => `ניסויים דומים ל־${id}:`,
  labNoSimilarFound: 'לא נמצאו ניסויים דומים.',

  labExperimentInputTitle: 'נתוני ניסוי לניתוח AI',
  labExperimentInputHint:
    'העלה קובץ ניסוי (PDF, TXT, CSV, JSON, XLSX/XLS) או הדבק/הקלד פרטי ניסוי למטה. קבצי Excel מומרים לטבלאות Markdown — יוצגו כטבלה ויישלחו כך ל־AI. עדכון קובץ: העלה שוב את ה־Excel ויחולף אותו מחדש.',
  labExcelTablePreview: 'תצוגת גיליון (כמו Excel)',
  labExcelShowRawForAi: 'הצגת טקסט Markdown ל־AI (מתקדם)',
  labExcelSheetTabsAria: 'גיליונות',
  labUploadExperimentFile: 'העלה קובץ ניסוי',
  labExperimentInputPlaceholder: 'הדבק כאן נתוני ניסוי, פורמולה, תוצאות, או תיאור...',
  labAiNeedContext: 'הזן או העלה נתוני ניסוי למעלה ואז בחר סוג ניתוח.',
  labAiThinking: 'מחשב...',
  labGetAiInsight: 'קבל תובנה מ־AI',
  labSendAsEmail: 'שלח במייל',
  labEmailSubjectPrefix: 'מעבדה – ',

  labSaveExperiment: 'שמור ניסוי',
  labSavedExperimentNamePlaceholder: 'שם לניסוי השמור',
  labSavedExperimentNameRequired: 'הזן שם לניסוי השמור.',
  labSavedExperimentContentRequired: 'הזן או העלה נתוני ניסוי לפני שמירה.',
  labSavedExperimentDeleteConfirm: 'למחוק את הניסוי השמור?',
  labSavedExperimentsTitle: 'ניסויים שמורים',
  labSavedExperimentsEmpty: 'אין ניסויים שמורים. הזן נתונים למעלה ושמור עם שם.',

  retry: 'נסה שוב',
  load: 'טען',
  refresh: 'רענן',
  validate: 'אמת',
  check: 'בדוק',

  dashboard: 'לוח בקרה',
  dashboardMainTitle: 'דשבורד ראשי',
  dashboardSubtitle: 'סקירה מרכזית של המעבדה – פרויקטים, ניסויים ופעילות.',
  dashboardRecentSectionTitle: 'פעילות ופריטים אחרונים',
  dashboardYourProjects: 'הפרויקטים שלך',
  dashboardProjectsMeta: (n) => (n === 0 ? 'אין עדיין פרויקטים' : n === 1 ? 'פרויקט אחד' : `${n} פרויקטים`),
  labStatsTitle: 'סטטיסטיקה של המעבדה',
  navDashboard: 'לוח בקרה',
  navProjects: 'פרויקטים',
  navExperiments: 'ניסויים',
  navMaterials: 'חומרים',
  navDocuments: 'מסמכים',
  navEmails: 'מיילים',
  navAnalysis: 'ניתוח',
  navSettings: 'הגדרות',
  recentActivity: 'פעילות אחרונה',
  recentExperiments: 'ניסויים אחרונים',
  recentDocuments: 'מסמכים אחרונים',
  quickActions: 'פעולות מהירות',
  quickActionNewProject: 'פרויקט חדש',
  quickActionExperiments: 'ניסויים',
  quickActionDocuments: 'מסמכים',
  quickActionProjects: 'לעמוד הפרויקטים',
  basicStats: 'סטטיסטיקה',
  experimentsSummary: 'סיכום ניסויים',
  successes: 'הצלחות',
  failures: 'כישלונות',
  openExperiments: 'ניסויים פתוחים',
  materialsAdded: 'חומרים שנוספו',
  researchActivity: 'פעילות מחקרית',
}
