/** Hebrew UI strings */
export default {
  appTitle: 'מערכת בקרת מעבדה',
  allProjects: 'כל הפרויקטים',
  projects: 'פרויקטים',
  newProject: 'פרויקט חדש',
  cancel: 'ביטול',
  create: 'צור',
  name: 'שם',
  description: 'תיאור',
  optional: 'אופציונלי',
  noDescription: 'אין תיאור',
  loading: 'טוען...',
  noProjectsYet: 'עדיין אין פרויקטים. צור אחד למעלה.',
  back: 'חזרה',

  overview: 'סקירה',
  overviewAnalytics: 'אנליטיקה',
  taskStatusBreakdown: 'התפלגות משימות',
  overdueTasks: 'משימות באיחור',
  milestonesProgress: 'התקדמות אבני דרך',
  byPriority: 'לפי עדיפות',
  noOverdue: 'אין משימות באיחור',
  completedMilestones: 'אבני דרך שהושלמו',
  tasks: 'משימות',
  milestones: 'אבני דרך',
  documents: 'מסמכים',
  notes: 'הערות',
  files: 'קבצים',
  rag: 'שאלות ותשובות',
  reports: 'דוחות',
  activity: 'פעילות',

  tasksCount: 'משימות',
  milestonesCount: 'אבני דרך',
  documentsCount: 'מסמכים',
  notesCount: 'הערות',
  filesCount: 'קבצים',

  addTask: 'הוסף משימה',
  taskTitle: 'כותרת משימה',
  todo: 'לביצוע',
  inProgress: 'בביצוע',
  inReview: 'בבדיקה',
  done: 'הושלם',
  cancelled: 'בוטל',
  low: 'נמוך',
  medium: 'בינוני',
  high: 'גבוה',
  add: 'הוסף',
  delete: 'מחיקה',
  deleteTaskConfirm: 'למחוק את המשימה?',
  noTasksYet: 'עדיין אין משימות',
  overdue: 'באיחור',
  markSelectedDone: 'סמן נבחרים כהושלמו',
  selectAll: 'בחר הכל',

  addMilestone: 'הוסף אבן דרך',
  sortByTitle: 'לפי כותרת',

  exportSummary: 'ייצא סיכום פרויקט',
  copyAnswer: 'העתק תשובה',
  copySuccess: 'הועתק ללוח',
  saveAnswerAsNote: 'שמור כהערה',
  saveAsNoteSuccess: 'נשמר כהערה בפרויקט',

  milestoneTitle: 'כותרת אבן דרך',
  deleteMilestoneConfirm: 'למחוק את אבן הדרך?',
  noMilestonesYet: 'עדיין אין אבני דרך',
  markAsCompleted: 'סמן כמושלמה',
  unmarkCompleted: 'בטל סימון',

  addDocument: 'הוסף מסמך',
  documentTitle: 'כותרת מסמך',
  content: 'תוכן',
  optionalContent: 'תוכן אופציונלי',
  save: 'שמירה',
  edit: 'עריכה',
  deleteDocumentConfirm: 'למחוק את המסמך?',
  noDocumentsYet: 'עדיין אין מסמכים',

  addNote: 'הוסף הערה',
  noteTitle: 'כותרת הערה',
  noteContent: 'תוכן ההערה',
  body: 'גוף',
  untitled: 'ללא כותרת',
  deleteNoteConfirm: 'למחוק את ההערה?',
  noNotesYet: 'עדיין אין הערות',

  uploadedFiles: 'קבצים שהועלו',
  uploadedFilesDesc: 'העלה PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה ואפשר לשאול עליהם בלשונית שאלות.',
  chooseFile: 'בחר קובץ להעלאה',
  uploading: 'מעלה...',
  remove: 'הסר',
  removeFileConfirm: 'להסיר את הקובץ מהפרויקט? (הוא יישאר במטריה עד להסרה משם.)',
  noFilesYet: 'עדיין לא הועלו קבצים.',
  download: 'הורדה',
  downloadNotAvailable: 'הורדת קובץ תעלה בגרסה הבאה.',

  docsManagementTab: 'ניהול מסמכים',
  docsManagementTitle: 'ניהול מסמכים',
  docsManagementIntro: 'העלה קבצים לפרויקט, הורד אותם או שאל שאלות על התוכן שלהם.',
  docsUploadSection: 'העלאת קבצים',
  docsUploadHint: 'PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה לעיבוד וניתן לשאול עליהם שאלות.',
  docsListSection: 'הקבצים בפרויקט',
  docsAskSection: 'שאל שאלה על המסמכים',
  docsAskHint: 'בחר קובץ (או כל הקבצים) ושאל שאלה – התשובה מבוססת על תוכן הקבצים במטריה.',

  ragTitle: 'שאלות (מטריה)',
  matriyaConnected: 'חיבור למטריה פעיל',
  matriyaNotSet: 'כתובת מטריה לא מוגדרת או לא זמינה (הגדר MATRIYA_BACK_URL ב־.env של maneger-back)',
  queryOver: 'חיפוש בתוך',
  allFiles: 'כל הקבצים',
  askQuestion: 'שאל שאלה',
  questionPlaceholder: 'הזן שאלה...',
  run: 'הרץ',
  running: 'מריץ...',

  title: 'כותרת',
  projectName: 'שם הפרויקט',

  settings: 'הגדרות',
  chat: "צ'אט",
  chatPlaceholder: 'כתוב הודעה...',
  chatSend: 'שלח',
  noChatYet: 'אין הודעות עדיין. תגיד שלום!',
  projectSettings: 'הגדרות פרויקט',
  editProject: 'ערוך פרויקט',
  deleteProject: 'מחיקת הפרויקט',
  deleteProjectConfirm: 'למחוק את הפרויקט וכל התוכן שלו (משימות, אבני דרך, מסמכים, הערות, קבצים)? לא ניתן לשחזר.',
  deleteProjectSuccess: 'הפרויקט נמחק.',
  saveChanges: 'שמור שינויים',

  dueDate: 'תאריך יעד',
  filterStatus: 'סנן לפי סטטוס',
  filterAll: 'הכל',
  sortBy: 'מיין לפי',
  sortByDate: 'תאריך',
  sortByPriority: 'עדיפות',

  milestoneDescription: 'תיאור אבן דרך',
  upcomingMilestones: 'אבני דרך קרובות',
  noUpcomingMilestones: 'אין אבני דרך קרובות.',
  taskProgress: 'התקדמות משימות',
  completed: 'הושלמו',

  searchProjects: 'חיפוש פרויקטים...',
  searchInList: 'חיפוש ברשימה...',
  noResults: 'לא נמצאו תוצאות.',

  notPartOfProject: 'אינך חלק מפרויקט זה.',
  sendRequestToOwner: 'שלח בקשת הצטרפות למנהל הפרויקט',
  requestPending: 'בקשתך ממתינה לאישור.',
  requestSent: 'הבקשה נשלחה.',
  members: 'חברים בפרויקט',
  pendingRequests: 'בקשות ממתינות',
  addMember: 'הוסף משתמש',
  addMemberPlaceholder: 'שם משתמש',
  selectUser: 'בחר משתמש',
  noUsersToAdd: 'אין משתמשים להוספה (כולם כבר בפרויקט, או שמשתמשים טרם התחברו למנהל).',
  approve: 'אשר',
  reject: 'דחה',
  owner: 'מנהל',
  member: 'חבר',
  userNotFound: 'משתמש לא נמצא. עליו להתחבר למנהל פעם אחת.',
  alreadyMember: 'כבר חבר בפרויקט.',
  noPendingRequests: 'אין בקשות ממתינות.',
  projectPermissions: 'הרשאות פרויקט',
  comingSoon: "בקרוב – פיצ'ר זה יופיע בגרסה הבאה.",
  removeFromProject: 'הסר מפרויקט',

  login: 'התחברות',
  signup: 'הרשמה',
  logout: 'יציאה',
  username: 'שם משתמש',
  password: 'סיסמה',
  email: 'דוא"ל',
  fullName: 'שם מלא',
  loginTitle: 'מערכת בקרת מעבדה',
  signupTitle: 'הרשמה – משתמשים כמו במטריה',
  loginButton: 'התחבר',
  signupButton: 'הירשם',
  noAccount: 'אין לך חשבון?',
  haveAccount: 'כבר יש לך חשבון?',
  loginError: 'שם משתמש או סיסמה שגויים.',
  signupError: 'ההרשמה נכשלה.',
}
