/** Hebrew UI strings */
export default {
  appTitle: 'מערכת בקרת מעבדה',
  allProjects: 'כל הפרויקטים',
  projects: 'פרויקטים',
  newProject: 'פרויקט חדש',
  cancel: 'ביטול',
  create: 'צור',
  name: 'שם',
  description: 'תיאור',
  optional: 'אופציונלי',
  noDescription: 'אין תיאור',
  loading: 'טוען...',
  noProjectsYet: 'עדיין אין פרויקטים. צור אחד למעלה.',
  back: 'חזרה',

  overview: 'סקירה',
  overviewAnalytics: 'אנליטיקה',
  taskStatusBreakdown: 'התפלגות משימות',
  overdueTasks: 'משימות באיחור',
  milestonesProgress: 'התקדמות אבני דרך',
  byPriority: 'לפי עדיפות',
  noOverdue: 'אין משימות באיחור',
  completedMilestones: 'אבני דרך שהושלמו',
  tasks: 'משימות',
  milestones: 'אבני דרך',
  documents: 'מסמכים',
  notes: 'הערות',
  files: 'קבצים',
  rag: 'שאלות ותשובות',
  reports: 'דוחות',
  activity: 'פעילות',

  tasksCount: 'משימות',
  milestonesCount: 'אבני דרך',
  documentsCount: 'מסמכים',
  notesCount: 'הערות',
  filesCount: 'קבצים',

  addTask: 'הוסף משימה',
  taskTitle: 'כותרת משימה',
  todo: 'לביצוע',
  inProgress: 'בביצוע',
  inReview: 'בבדיקה',
  done: 'הושלם',
  cancelled: 'בוטל',
  low: 'נמוך',
  medium: 'בינוני',
  high: 'גבוה',
  add: 'הוסף',
  delete: 'מחיקה',
  deleteTaskConfirm: 'למחוק את המשימה?',
  noTasksYet: 'עדיין אין משימות',
  overdue: 'באיחור',
  markSelectedDone: 'סמן נבחרים כהושלמו',
  selectAll: 'בחר הכל',

  addMilestone: 'הוסף אבן דרך',
  sortByTitle: 'לפי כותרת',

  exportSummary: 'ייצא סיכום פרויקט',
  copyAnswer: 'העתק תשובה',
  copySuccess: 'הועתק ללוח',
  saveAnswerAsNote: 'שמור כהערה',
  saveAsNoteSuccess: 'נשמר כהערה בפרויקט',

  milestoneTitle: 'כותרת אבן דרך',
  deleteMilestoneConfirm: 'למחוק את אבן הדרך?',
  noMilestonesYet: 'עדיין אין אבני דרך',
  markAsCompleted: 'סמן כמושלמה',
  unmarkCompleted: 'בטל סימון',

  addDocument: 'הוסף מסמך',
  documentTitle: 'כותרת מסמך',
  content: 'תוכן',
  optionalContent: 'תוכן אופציונלי',
  save: 'שמירה',
  edit: 'עריכה',
  deleteDocumentConfirm: 'למחוק את המסמך?',
  noDocumentsYet: 'עדיין אין מסמכים',

  addNote: 'הוסף הערה',
  noteTitle: 'כותרת הערה',
  noteContent: 'תוכן ההערה',
  body: 'גוף',
  untitled: 'ללא כותרת',
  deleteNoteConfirm: 'למחוק את ההערה?',
  noNotesYet: 'עדיין אין הערות',

  uploadedFiles: 'קבצים שהועלו',
  uploadedFilesDesc: 'העלה PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה ואפשר לשאול עליהם בלשונית שאלות.',
  chooseFile: 'בחר קובץ להעלאה',
  chooseFileMultiple: 'העלה קבצים מהמחשב שלך',
  uploadFromComputer: 'העלה מהמחשב',
  uploadChoiceTitle: 'מה להעלות?',
  uploadFilesOption: 'קבצים',
  uploadFolderOption: 'תיקייה',
  chooseFromSharepoint: 'ייבוא קבצים מ-SharePoint',
  uploadToSharepoint: 'העלה קבצים/תיקיות ל-SharePoint',
  uploadToSharepointManual: 'העלה קובץ או תיקייה ידנית',
  sharepointFolderPath: 'נתיב תיקייה (אופציונלי)',
  sharepointFolderName: 'שם תיקייה (לכמה קבצים)',
  sharepointUploadSuccess: 'הקבצים הועלו ל-SharePoint.',
  sharepointUploadSomeFailed: 'חלק מהקבצים לא הועלו.',
  sharepointBucketList: 'קבצים מ-SharePoint',
  addToProject: 'הוסף לפרויקט',
  addFolderToProject: 'הוסף תיקייה לפרויקט',
  loadingSharepointFiles: 'טוען רשימה...',
  noSharepointFiles: 'אין קבצים בדלי.',
  searchSharepointFiles: 'חיפוש קבצים...',
  folder: 'תיקייה',
  uploading: 'מעלה...',
  uploadingProgress: (current, total) => `מעלה ${current} / ${total}`,
  uploadSomeFailed: 'חלק מההעלאות נכשלו:',
  remove: 'הסר',
  removeFileConfirm: 'להסיר את הקובץ מהפרויקט? (הוא יישאר במטריה עד להסרה משם.)',
  noFilesYet: 'עדיין לא הועלו קבצים.',
  noFolder: 'ללא תיקייה',
  fileIndexError: 'קובץ זה לא ניתן לסריקה עקב פורמט לא תואם',
  fileCannotBeIndexed: 'לא ניתן לשאול על קובץ זה – פורמט לא נתמך',
  download: 'הורדה',
  downloadNotAvailable: 'הורדת קובץ תעלה בגרסה הבאה.',

  docsManagementTab: 'ניהול מסמכים',
  docsManagementTitle: 'ניהול מסמכים',
  docsManagementIntro: 'העלה קבצים לפרויקט, הורד אותם או שאל שאלות על התוכן שלהם.',
  docsUploadSection: 'העלאת קבצים',
  docsUploadHint: 'PDF, DOCX, TXT, XLSX. הקבצים נשלחים למטריה לעיבוד וניתן לשאול עליהם שאלות.',
  docsListSection: 'הקבצים בפרויקט',
  docsAskSection: 'שאל שאלה על המסמכים',
  docsAskHint: 'בחר קובץ (או כל הקבצים) ושאל שאלה – התשובה מבוססת על תוכן הקבצים במטריה.',

  ragTitle: 'שאלות (מטריה)',
  matriyaConnected: 'חיבור למטריה פעיל',
  matriyaNotSet: 'כתובת מטריה לא מוגדרת או לא זמינה (הגדר MATRIYA_BACK_URL ב־.env של maneger-back)',
  ragConnected: 'חיבור ל־RAG פעיל',
  ragNotAvailable: 'חיבור ל־RAG לא פעיל. בדוק ש־POSTGRES_URL ו־OPENAI_API_KEY מוגדרים ב־maneger-back (Vercel).',
  queryOver: 'חיפוש בתוך',
  allFiles: 'כל הקבצים',
  selectFileToAsk: 'בחר קובץ לשאלה',
  askQuestion: 'שאל שאלה',
  questionPlaceholder: 'הזן שאלה...',
  run: 'הרץ',
  running: 'מריץ...',

  title: 'כותרת',
  projectName: 'שם הפרויקט',

  settings: 'הגדרות',
  chat: "צ'אט",
  chatPlaceholder: 'כתוב הודעה...',
  chatSend: 'שלח',
  noChatYet: 'אין הודעות עדיין. תגיד שלום!',
  projectSettings: 'הגדרות פרויקט',
  editProject: 'ערוך פרויקט',
  deleteProject: 'מחיקת הפרויקט',
  deleteProjectConfirm: 'למחוק את הפרויקט וכל התוכן שלו (משימות, אבני דרך, מסמכים, הערות, קבצים)? לא ניתן לשחזר.',
  deleteProjectSuccess: 'הפרויקט נמחק.',
  saveChanges: 'שמור שינויים',

  dueDate: 'תאריך יעד',
  filterStatus: 'סנן לפי סטטוס',
  filterAll: 'הכל',
  sortBy: 'מיין לפי',
  sortByDate: 'תאריך',
  sortByPriority: 'עדיפות',

  milestoneDescription: 'תיאור אבן דרך',
  upcomingMilestones: 'אבני דרך קרובות',
  noUpcomingMilestones: 'אין אבני דרך קרובות.',
  taskProgress: 'התקדמות משימות',
  completed: 'הושלמו',

  searchProjects: 'חיפוש פרויקטים...',
  searchInList: 'חיפוש ברשימה...',
  noResults: 'לא נמצאו תוצאות.',

  notPartOfProject: 'אינך חלק מפרויקט זה.',
  sendRequestToOwner: 'שלח בקשת הצטרפות למנהל הפרויקט',
  requestPending: 'בקשתך ממתינה לאישור.',
  requestSent: 'הבקשה נשלחה.',
  members: 'חברים בפרויקט',
  pendingRequests: 'בקשות ממתינות',
  addMember: 'הוסף משתמש',
  addMemberPlaceholder: 'שם משתמש',
  selectUser: 'בחר משתמש',
  noUsersToAdd: 'אין משתמשים להוספה (כולם כבר בפרויקט, או שמשתמשים טרם התחברו למנהל).',
  approve: 'אשר',
  reject: 'דחה',
  owner: 'מנהל',
  member: 'חבר',
  userNotFound: 'משתמש לא נמצא. עליו להתחבר למנהל פעם אחת.',
  alreadyMember: 'כבר חבר בפרויקט.',
  noPendingRequests: 'אין בקשות ממתינות.',
  projectPermissions: 'הרשאות פרויקט',
  comingSoon: "בקרוב – פיצ'ר זה יופיע בגרסה הבאה.",
  removeFromProject: 'הסר מפרויקט',

  login: 'התחברות',
  signup: 'הרשמה',
  logout: 'יציאה',
  username: 'שם משתמש',
  password: 'סיסמה',
  email: 'דוא"ל',
  fullName: 'שם מלא',
  loginTitle: 'מערכת בקרת מעבדה',
  signupTitle: 'הרשמה – משתמשים כמו במטריה',
  loginButton: 'התחבר',
  signupButton: 'הירשם',
  noAccount: 'אין לך חשבון?',
  haveAccount: 'כבר יש לך חשבון?',
  loginError: 'שם משתמש או סיסמה שגויים.',
  signupError: 'ההרשמה נכשלה.',

  labTab: 'מעבדה',
  labExperiments: 'ניסויים',
  labExperimentsList: 'רשימת ניסויים',
  labExperimentsCount: (n) => `${n} ניסויים`,
  labSessionsCount: (n) => `${n} סשני מחקר`,
  labMaterialsCount: (n) => `${n} חומרים בספרייה`,
  labInsights: 'תובנות מהדאטה',
  labInsightsSummary: 'סיכום:',
  labSuccessRate: 'הצלחה',
  labFailures: 'כישלונות',
  labByDomain: 'לפי תחום',
  labByMaterial: 'לפי חומר (בכישלונות)',
  labLoadInsights: 'לחץ רענן לטעינת תובנות.',
  labContradictions: 'זיהוי סתירות',
  labContradictionsFound: (n) => `נמצאו ${n} סתירות (אותה פורמולה, תוצאות שונות).`,
  labNoContradictions: 'לא נמצאו סתירות.',
  labSameFormulaDifferentOutcomes: 'אותה פורמולה – תוצאות שונות:',
  labFailurePatterns: 'דפוסי כישלון',
  labFailureCount: (n) => `${n} ניסויים נכשלו או חלקיים.`,
  labResearchSnapshot: 'ניתוח סנאפשוט מחקר',
  labSnapshotTotal: (n) => `סה"כ ${n} ניסויים בסנאפשוט.`,
  labFormulaValidator: 'אימות פורמולה (בסיסי)',
  labFormulaPlaceholder: 'הדבק פורמולה או הרכב...',
  labFormulaValid: 'הפורמולה תקינה.',
  labFormulaInvalid: 'נמצאו בעיות בפורמולה.',
  labSimilarExperiments: 'ניסויים דומים',
  labRelations: 'קשרים (ניסוי / פורמולה / חומר / תוצאה)',
  labRelationsSummary: (expCount, matCount) => `${expCount} ניסויים, ${matCount} חומרים בספרייה.`,
  labRelationsList: 'קשרים נגזרים מהדאטה:',
  labResearchGuard: 'Research Guard',
  labSuggestionEngine: 'Suggestion Engine',
  labAnalysisType: 'סוג ניתוח',
  labSuggestionEngineHint: 'מנוע ההצעות מנתח ניסויים קיימים ומציע 3–5 ניסויים חדשים (אזורים לא נבדקים, גבולות יציבות, קומבינציות חומרים). הזן או העלה נתוני ניסוי למעלה ולחץ לקבלת הצעות.',
  labGuardPlaceholder: 'הדבק פורמולה לבדיקה (כפילות, אזהרות)...',
  labGuardAllowed: 'מותר להמשיך.',
  labGuardBlocked: 'קיימות אזהרות.',
  labShowingFirst: (n) => `מציג את ${n} הראשונים.`,

  labFormulationIntelligence: 'Formulation Intelligence',
  labFormulationIntelligenceHint: 'בדיקה לפני ניסוי: מאזן מסה, טווחים, התאמה לניסויים שנכשלו.',
  labFormulationPlaceholder: 'פורמולה או JSON: { "formula": "...", "domain": "...", "materials": [], "percentages": {} }',
  labStatus: 'סטטוס',
  labSimilarExperimentsTitle: 'ניסויים דומים',
  labSimilarExperimentsHint: 'הזן מזהה ניסוי (experiment_id או id) כדי למצוא ניסויים דומים לפי חומרים ופרופורציות.',
  labExperimentIdPlaceholder: 'experiment_id או UUID',
  labSimilarTo: (id) => `ניסויים דומים ל־${id}:`,
  labNoSimilarFound: 'לא נמצאו ניסויים דומים.',

  labExperimentInputTitle: 'נתוני ניסוי לניתוח AI',
  labExperimentInputHint: 'העלה קובץ ניסוי (TXT, CSV, JSON, XLSX) או הדבק/הקלד פרטי ניסוי למטה. אחר כך בחר סוג ניתוח למעלה.',
  labUploadExperimentFile: 'העלה קובץ ניסוי',
  labExperimentInputPlaceholder: 'הדבק כאן נתוני ניסוי, פורמולה, תוצאות, או תיאור...',
  labAiNeedContext: 'הזן או העלה נתוני ניסוי למעלה ואז בחר סוג ניתוח.',
  labAiThinking: 'מחשב...',
  labGetAiInsight: 'קבל תובנה מ־AI',

  labSaveExperiment: 'שמור ניסוי',
  labSavedExperimentNamePlaceholder: 'שם לניסוי השמור',
  labSavedExperimentNameRequired: 'הזן שם לניסוי השמור.',
  labSavedExperimentContentRequired: 'הזן או העלה נתוני ניסוי לפני שמירה.',
  labSavedExperimentDeleteConfirm: 'למחוק את הניסוי השמור?',
  labSavedExperimentsTitle: 'ניסויים שמורים',
  labSavedExperimentsEmpty: 'אין ניסויים שמורים. הזן נתונים למעלה ושמור עם שם.',

  retry: 'נסה שוב',
  load: 'טען',
  refresh: 'רענן',
  validate: 'אמת',
  check: 'בדוק',

  dashboard: 'לוח בקרה',
  navDashboard: 'לוח בקרה',
  navProjects: 'פרויקטים',
  navExperiments: 'ניסויים',
  navMaterials: 'חומרים',
  navDocuments: 'מסמכים',
  navAnalysis: 'ניתוח',
  navSettings: 'הגדרות',
  recentActivity: 'פעילות אחרונה',
  recentExperiments: 'ניסויים אחרונים',
  basicStats: 'סטטיסטיקה',
  experimentsSummary: 'סיכום ניסויים',
  successes: 'הצלחות',
  failures: 'כישלונות',
  openExperiments: 'ניסויים פתוחים',
  materialsAdded: 'חומרים שנוספו',
  researchActivity: 'פעילות מחקרית',
}
